spring.application.name=api
server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
aws.accessKeyId=${AWS_ACCESS_KEY}
aws.secretAccessKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_BUCKET_NAME}
# CONFIGURACOES TWILIO (Lidas diretamente do Railway)
twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_TOKEN}
twilio.phone.number=${TWILIO_PHONE}